### ISSUE TITLE
Bug: "Santa Monica" (cityId: `1652792`) returns "ENTITY_NOT_FOUND"

### ISSUE THREAD

**Issue by brandon206** [wirefreethought/geodb#1]
**Describe the bug**
Endpoint (`https://wft-geo-db.p.rapidapi.com/v1/geo/cities/1652792`) returns 404 NOT Found.
```
{
    "errors": [
        {
            "code": "ENTITY_NOT_FOUND",
            "message": "Place with id '1652792' not found"
        }
    ]
}
```

**To Reproduce**
1. Try and fetch the result of endpoint (`https://wft-geo-db.p.rapidapi.com/v1/geo/cities/1652792`)
2. See error

**Expected behavior**
This should output the correct data in the following structure:
```
example of what "Venice" looks like:
{
    "data": {
        "id": 126157,
        "wikiDataId": "Q773853",
        "type": "CITY",
        "city": "Venice",
        "name": "Venice",
        "country": "United States of America",
        "countryCode": "US",
        "region": "California",
        "regionCode": "CA",
        "elevationMeters": 4,
        "latitude": 33.990833333,
        "longitude": -118.459166666,
        "population": 40885,
        "timezone": "America__Los_Angeles",
        "distance": null,
        "deleted": false,
        "placeType": "CITY"
    }
}
```

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Macbook
 - OS: macOS Monterey v.12
 - Browser: Google Chrome / Postman
 - Google Chrome Version: 103.0.5060.53 (Official Build) (arm64)

**Additional context**
This error is causing the endpoint I need (`https://wft-geo-db.p.rapidapi.com/v1/geo/cities/126792/distance?toCityId=1652792`) to return a 404 error. If I use any different city instead of Santa Monica (`cityId: 1652792`). It works fine.

**Comment by wirefreethought** [comment]
```
GET /v1/geo/cities?countryIds=US&namePrefix=Santa%20Monica

- Santa Monica, CA (id: 3249795)
- Santa Monica, TX (id: 126087)
```

It's possible that you've cached on an old id that became invalid due to a mass data refresh in recent months. The more reliable way to reference cities is to use the Wikidata ID which should never change (regardless of any possible GeoDB data refreshes).

At any rate, this call works:

`GET /v1/geo/cities/126792/distance?toCityId=3249795`

**Comment by brandon206** [comment]
Thank you! That is it! I have an old id cached. That is great to know, I'll have to use that `Wikidata ID` instead.
